### ISSUE TITLE
Change `=` to `<-`

### ISSUE THREAD

**Issue by KrystynaGrzesiak** [hadexversum/powerHaDeX#11]
- [x] create_experimental_file.R
- [x] exchange_rates.R
- [x]  isotopic_distribution.R
- [x] noisy_spectra.R
- [x]  plots.R
- [x] power.R
- [x] powerHaDeX-package.R
- [x] RcppExports.R
- [x] simulate_HD_exchange.R
- [x] simulate_theoretical_spectra.R
- [x] statistical_tests.R

**Comment by mstaniak** [comment]
COME ON
